Update app.py
Fixing issue of: 

TypeError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/mount/src/logistic-regression-handwriting/app.py", line 56, in <module>
    st.image(image_bytes, caption='Uploaded Image', use_column_width=True)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.14/site-packages/streamlit/runtime/metrics_util.py", line 596, in wrapped_func
    result = non_optional_func(*args, **kwargs)